name: derma_care
description: "A new Flutter project."
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ^3.24.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^3.1.0

flutter:
  uses-material-design: true
